name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: italiapersonalfinance
        uses: actions/checkout@v2
          
      - name: Add upstream repo
        run: git remote add upstream https://github.com/emish89/italiapersonalfinance.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes to fork
        run: git push origin main